config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only:[:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :users, only:[:show, :edit, :update]
  resources :tags, only: [:index, :show]
  scope module: :prototypes do
    resources :popular, only: :index
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :count
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  has_many :prototype_images, dependent: :delete_all
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :prototype_images
  validates :title, :catchcopy, :concept, presence: true

  acts_as_taggable_on :prototypes
  acts_as_taggable

  def like_user(user)
   likes.find_by(user_id: user)
  end
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
  belongs_to :prototype
  mount_uploader :content, PrototypeImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prototypes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :member, :profile, :works, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_prototype, only: [:create]


  def create
    @comments = @prototype.comments.includes(:user, :prototype)
    comment = @prototype.comments.create(comment_params)

  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

  def find_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

before_action :find_prototype ,only:[:create, :destroy]

  def create
    @like = @prototype.likes.create(user_id: current_user.id)
    @prototype.reload
  end

  def destroy
    @prototype.likes.find_by(params[:user_id]).destroy
    @prototype.reload
  end

  private
  def find_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).order("count DESC").page(params[:page]).per(8)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :find_prototype ,only:[:show,:edit,:destroy,:update]

  def index
    @prototypes = Prototype.all.order("created_at DESC").page(params[:page]).per(8)
  end

  def show
    @likes = @prototype.likes
    @comment = Comment.new
    @comments = @prototype.comments
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
       redirect_to root_path, notice: "Saved prototype Successfully"
     else
      render :new, alert: 'Save to failure'
    end
  end

  def edit
  end

  def update
    if @prototype.update(prototype_params)
       redirect_to root_path, notice: "Saved prototype Successfully"
      else
        render :update, alert: "Could not be updated"
    end
  end

  def destroy
    if @prototype.user_id == current_user.id
      @prototype.destroy
      redirect_to root_path, notice: "Deleted prototype Successfully"
    end
  end

  private
  def prototype_params
      params.require(:prototype).permit(:title, :catchcopy, :concept, prototype_images_attributes: [:id, :status, :content]).merge(tag_list: params[:prototype][:tag])
  end

  private
  def find_prototype
    @prototype = Prototype.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag).includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user ,only:[:show,:edit]

  def show
    @prototype = @user.prototypes.order("created_at DESC").page(params[:page]).per(8)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
       redirect_to root_url, notice: "Updated Profile Successfully"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :member, :profile, :works, :avatar, :email)
  end

  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/comments/create.js.erb
$("#comment_form").val("");
$("#all_comments").html("<%= j(render partial: 'prototypes/comment') %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
    = link_to root_path ,class: "navbar-brand" do
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{aria: { expanded: "false" }, data: { toggle: "dropdown" }, href: "#", role: "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "My Page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path

app/views/layouts/_message.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    =link_to "x", '#', class: "close", data:{dismiss: "alert"}
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http:{equiv: "Content-Type"}}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true }}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render 'layouts/message'
    = yield
    = render "layouts/footer"

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'prototypes/like', locals: {prototype: @prototype, like: @likes}) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'prototypes/like', locals: {prototype: @prototype, like: @likes}) %>");

app/views/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        - if current_page?(popular_index_path)
          %li.active{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li{role: "presentation"}
            =link_to "Newest PROTO",root_path
        - else
          %li{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li.active{role: "presentation"}
            =link_to "Newest PROTO",root_path
      =button_tag "View Tags",type: "button",class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render @prototypes

.text-center
  %ul.pagination
    %li.disabled
      =link_to '#',aria: {label: "Previous"} do
        %span{area: {hidden:true}} «
    %li.active
      =link_to '/' do
        %span.sr-only (current)
    %li
      =link_to "2",'#'
    %li
      =link_to "3",'#'
    %li
      =link_to "4",'#'
    %li
      =link_to "5",'#'
    %li
      =link_to '#',aria: {label: "Next"} do
        %span{area: {hidden:true}} »

app/views/prototypes/_comment.html.haml
- @comments.each do|comment|
  .media
    .media-left
      = link_to image_tag("#{@prototype.user.avatar}", size: "64x64", class: "media-object")
    .media-body
      %h4#top-aligned-media.media-heading
        = comment.user.name
        = link_to '#top-aligned-media',class: "anchorjs-link" do
          %span.anchorjs-icon
      %p= comment.text

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user)
    = button_to prototype_like_path(prototype,like), method: :delete, class: "btn btn-default", id: "like-button", remote: true do
      = image_tag("icon_heart_red.svg")
      Like
      %span.num= prototype.count
  - else
    = button_to prototype_likes_path(prototype), class: "btn btn-default", id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      Like
      %span.num= prototype.count
-else
  = image_tag("icon_heart.svg")
  Like
  %span.num= prototype.count

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  -if user_signed_in? && prototype.user.id == current_user.id
    .dropdown.drop_menu_location
      %a.btn.btn-default.dropdown-toggle#dropdownMenu{aria: { expanded: "false" }, data: { toggle: "dropdown" }, href: "#", role: "button"}
        Action
      %ul.dropdown-menu{role: "menu",aria: { labelledby: "dropdownMenu1"}}
        %li
          = link_to "Delete", prototype_path(prototype), method: :delete
        %li
          = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag (prototype.prototype_images.first.content)
    .caption
      %h3
        = prototype.title
        .proto-meta
          .proto-user
            =link_to "by#{prototype.user.name}", user_path(current_user)
          .proto-posted
            = prototype.created_at.strftime("%b %d")
      %ul.proto-tag-list.list-inline
        -prototype.tags.each do |tag|
          %li
            =link_to tag.name, tag_path(tag), class: "btn btn-default"

app/views/prototypes/edit.html.haml
= form_for @prototype, html: {class: 'container proto-new'}  do |f|
  - if @prototype.errors.any?
    .alert.alert-danger
      %h2
        = pluralize(@prototype.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @prototype.errors.full_messages.each do |message|
          %li= message

  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: 'proto-new-title'
    .row
      .col-md-12
        .cover-image-upload
          = f.fields_for :prototype_images do |proto_main_image|
            = proto_main_image.file_field :content, class: "input_img"
            .review_img
            = proto_main_image.hidden_field :status, value: 'main_image'
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :prototype_images do |proto_sub_image|
                = proto_sub_image.file_field :content, class: "input_sub_img"
                .review_sub_img
                = proto_sub_image.hidden_field :status, value: 'sub_images'
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :prototype_images do |proto_sub_image|
                = proto_sub_image.file_field :content, class: "input_sub02_img"
                .review_sub02_img
                = proto_sub_image.hidden_field :status, value: 'sub_images'
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: 'Catch Copy'
      .col-md-12
        = f.text_area :concept, cols: '30', rows: '4', placeholder: 'Concept'
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "Web desgin"
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "UI"
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "Application"
    .row.text-center.proto-btn
      =button_tag "Publish",type: "submit",class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        - if current_page?(popular_index_path)
          %li.active{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li{role: "presentation"}
            =link_to "Newest PROTO",root_path
        - else
          %li{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li.active{role: "presentation"}
            =link_to "Newest PROTO",root_path
      =link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render @prototypes

.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
= form_for @prototype, html: {class: 'container proto-new'}  do |f|
  - if @prototype.errors.any?
    .alert.alert-danger
      %h2
        = pluralize(@prototype.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @prototype.errors.full_messages.each do |message|
          %li= message

  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: 'proto-new-title'
    .row
      .col-md-12
        .cover-image-upload
          = f.fields_for :prototype_images do |proto_main_image|
            = proto_main_image.file_field :content, class: "input_img"
            .review_img
            = proto_main_image.hidden_field :status, value: 'main_image'
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :prototype_images do |proto_sub_image|
                = proto_sub_image.file_field :content, class: "input_sub_img"
                .review_sub_img
                = proto_sub_image.hidden_field :status, value: 'sub_images'
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :prototype_images do |proto_sub_image|
                = proto_sub_image.file_field :content, class: "input_sub02_img"
                .review_sub02_img
                = proto_sub_image.hidden_field :status, value: 'sub_images'
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: 'Catch Copy'
      .col-md-12
        = f.text_area :concept, cols: '30', rows: '4', placeholder: 'Concept'
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "Web desgin"
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "UI"
          .col-md-3
            =text_field_tag 'prototype[tag][]', "", placeholder: "Application"
    .row.text-center.proto-btn
      =button_tag "Publish",type: "submit",class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        - if current_page?(popular_index_path)
          %li.active{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li{role: "presentation"}
            =link_to "Newest PROTO",root_path
        - else
          %li{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li.active{role: "presentation"}
            =link_to "Newest PROTO",root_path
      =link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(current_user) do
            = image_tag @prototype.user.avatar, class: 'media-object', size: '64x64', alt: 'no-image'
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            = link_to "by#{@prototype.user.name}",user_path(current_user)
            %span.degree #{@prototype.user.profile}

    .col-md-6.text-right#like-button
      = render partial: 'prototypes/like', locals: {prototype: @prototype, like: @likes}

  .row
    .col-md-9
      = image_tag @prototype.prototype_images.first.content, class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag @prototype.prototype_images.second.content, class: 'img-responsive'
        %li.list-group-item
          = image_tag @prototype.prototype_images.third.content, class: 'img-responsive'

  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p=@prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p=@prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        -@prototype.tags.each do |tag|
          %li
            =link_to tag.name, tag_path(tag), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (#{@prototype.comments.count})
    .col-md-8#all_comments
      =render partial: 'prototypes/comment'

      .form-inline
        - if user_signed_in?
          = form_for [@prototype, @comment], remote: true do |f|
            %h4 Write a comment
            .row
              .form-group.col-md-10
                = f.text_area :text, placeholder: "Your comments", class: "form-control", rows: "3", id: "comment_form"
              .form-group.col-md-2
                = f.submit "Comment", class: "btn btn-primary"

app/views/tags/_tag.html.haml
%li.col-md-4
  = link_to tag.name, tag_path(tag), class: "btn btn-default"
  %p #{tag.taggings_count} projects

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tag List
      %ul
        = render partial: 'tags/tag', collection: @tags

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        - if current_page?(popular_index_path)
          %li.active{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li{role: "presentation"}
            =link_to "Newest PROTO",root_path
        - else
          %li{role: "presentation"}
            =link_to "Popular PROTO",popular_index_path
          %li.active{role: "presentation"}
            =link_to "Newest PROTO",root_path
      =button_tag "View Tags",type: "button",class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
      =link_to '#',aria: {label: "Previous"} do
        %span{area: {hidden:true}} «
    %li.active
      =link_to '/' do
        %span.sr-only (current)
    %li
      =link_to "2",'#'
    %li
      =link_to "3",'#'
    %li
      =link_to "4",'#'
    %li
      =link_to "5",'#'
    %li
      =link_to '#',aria: {label: "Next"} do
        %span{area: {hidden:true}} »

app/views/users/edit.html.haml
= form_for current_user, html: {class: 'container user-new'}  do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            = f.text_field :name, placeholder: 'Username'
          .user-image.col-md-2
            %button.btn.btn-primary Change image
            = f.file_field :avatar, class: "avatar_input"
            .avatar_img
        = f.email_field :email, placeholder: 'E-Mail', class: 'user-email'
        = f.password_field :password, placeholder: 'Password', class: 'input user-password'
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            = f.text_field :member, placeholder: 'Member'
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            = f.text_area :profile, cols: '30', rows: '4', placeholder: 'Profile'
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            = f.text_area :works, cols: '30', rows: '4', placeholder: 'Works'
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Save

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        =link_to '#' do
          = image_tag '', class: 'media-object', alt: '64x64', data: { holder:{ rendered: true }, src: 'holder.js/64x64', style: 'width: 64px; height: 64px;'}
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p #{@user.profile}
          .col-md-6
            %h4 Works
            %p #{@user.works}
.container.proto-list
  .row
    =render @prototype

.text-center
  = paginate(@prototype)